### ISSUE TITLE
[TlsLayer]: Failed with start_tls over a non-idle stream

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#145]
I had tried with setting max-connection to 1, and the problem gone.
So I guess it's a race condition problem.

When we start_tls before IOStream read the buffer from source(about TLS handshaking), it works fine.
But when we start_tls after, it would failed.

I had tried pause just after socks handshaking finish, and resume it before start_tls, and it works find.
So I guess that maybe the cert/key generation on TlsLayer consume too much time that cause the problem, and I tried pause before cert/key generation, and resume after done, but still failed...

There is a workaround, but not a good solution...

Here is the stacktrace

```
2016-08-30 10:49:10,725 - proxy                          - ERROR    - IOStream is not idle; cannot detach
Traceback (most recent call last):
  File "/Users/han-pc/workspace/python/microProxy/microproxy/proxy.py", line 127, in handle_stream
    yield self.layer_manager.run_layers(initial_context)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/proxy.py", line 31, in run_layers
    current_context = yield current_layer.process_and_return_context()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/layer/application/tls.py", line 96, in process_and_return_context
    server_side=True, ssl_options=src_ssl_ctx)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/iostream.py", line 45, in start_tls
    socket = self.detach()
  File "/Users/han-pc/workspace/python/microProxy/microproxy/iostream.py", line 35, in detach
    raise ValueError("IOStream is not idle; cannot detach")
ValueError: IOStream is not idle; cannot detach
```

**Comment by mike820324** [comment]
I'll work on it, when I'm available.
