### ISSUE TITLE
[ReplayLayer]: Replay http/2 request with body failed

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#176]
I'm not sure what happen, but maybe there is some bug in replay that it didn't send request body content correctly.

Stacktrace

```
Traceback (most recent call last):
  File "/Users/han-pc/workspace/python/microProxy/microproxy/event/replay.py", line 35, in handle
    self._send_http2_request(write_stream, viewer_context)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/event/replay.py", line 69, in _send_http2_request
    conn.send_request(stream_id, context.request)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/protocol/http2.py", line 177, in send_request
    self.send_data(stream_id, request.body)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/protocol/http2.py", line 212, in send_data
    self.flush()
  File "/Users/han-pc/workspace/python/microProxy/microproxy/protocol/http2.py", line 55, in flush
    return self.stream.write(data)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/iostream.py", line 376, in write
    assert isinstance(data, bytes)
AssertionError
```

**Comment by chhsiao90** [comment]
duplicate #173 
Found that it's same problem that replay request didn't decode base64
