### ISSUE TITLE
[SocksLayer]: unittest failed after update library

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#209]
After update socks5 version from [mike820324/socks5](https://github.com/mike820324/socks5) that seems to introduce regression and the unit test failed.

```
======================================================================
ERROR: test_greeting_with_wrong_socks_version (microproxy.test.layer.test_socks.TestSocksProxyHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 132, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 525, in post_coroutine
    timeout=timeout)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/test/layer/test_socks.py", line 101, in test_greeting_with_wrong_socks_version
    GreetingRequest(4, 2, (AUTH_TYPE["NO_AUTH"], AUTH_TYPE["GSSAPI"])))
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/src/socks5/socks5/events.py", line 23, in __init__
    raise ValueError("Only support socks version 5")
ValueError: Only support socks version 5

======================================================================
ERROR: test_handle_connection_timeout (microproxy.test.layer.test_socks.TestSocksProxyHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 132, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 525, in post_coroutine
    timeout=timeout)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/test/layer/test_socks.py", line 188, in test_handle_connection_timeout
    "1.2.3.4", self.port)
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/src/socks5/socks5/events.py", line 130, in __init__
    raise ValueError("Invalid ipaddress format")
ValueError: Invalid ipaddress format

======================================================================
ERROR: test_handle_stream_closed (microproxy.test.layer.test_socks.TestSocksProxyHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 132, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 525, in post_coroutine
    timeout=timeout)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/test/layer/test_socks.py", line 212, in test_handle_stream_closed
    "1.2.3.4", self.port)
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/src/socks5/socks5/events.py", line 130, in __init__
    raise ValueError("Invalid ipaddress format")
ValueError: Invalid ipaddress format

======================================================================
ERROR: test_process_and_return_context (microproxy.test.layer.test_socks.TestSocksProxyHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 132, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 525, in post_coroutine
    timeout=timeout)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/test/layer/test_socks.py", line 269, in test_process_and_return_context
    client_socks_conn.initialiate_connection()
AttributeError: 'ClientConnection' object has no attribute 'initialiate_connection'

======================================================================
ERROR: test_socks_request_ipv4 (microproxy.test.layer.test_socks.TestSocksProxyHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 132, in __call__
    result = self.orig_method(*args, **kwargs)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/testing.py", line 525, in post_coroutine
    timeout=timeout)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/ioloop.py", line 453, in run_sync
    return future_cell[0].result()
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.pyenv/versions/mp/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/test/layer/test_socks.py", line 115, in test_socks_request_ipv4
    "127.0.0.1", self.port))
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/src/socks5/socks5/events.py", line 130, in __init__
    raise ValueError("Invalid ipaddress format")
ValueError: Invalid ipaddress format
```

**Comment by mike820324** [comment]
I'll publish a new version 0.4.1 due to this issue. Sorry for the inconvenience.

**Comment by chhsiao90** [comment]
Please remember update version.py!
