### ISSUE TITLE
[mpdump]: mpdump should have default argument defined

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#218]
When I tried the latest version mpdump on master with following steps
```
pip install . -U
mpdump
```

It display error as
```
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/bin/mpdump", line 11, in <module>
    load_entry_point('microProxy==0.4.1+dev', 'console_scripts', 'mpdump')()
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/lib/python2.7/site-packages/microproxy/command_line.py", line 222, in mpdump
    config = parse_config(config_field_info)
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/lib/python2.7/site-packages/microproxy/config.py", line 140, in parse_config
    verify_config(config_field_info, config)
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/lib/python2.7/site-packages/microproxy/config.py", line 113, in verify_config
    raise KeyError("missing config field: [{0}]".format(",".join(missing_fields)))
KeyError: 'missing config field: [viewer_port,proxy_host,events_port]'
```

I think the error shouldn't be displayed that it need pre-defined default config.

**Comment by mike820324** [comment]
hmm, indeed we should put some default value in the config options. 

```
proxy_host=127.0.0.1
viewer_port=5581
events_port=5582
```

**Comment by mike820324** [comment]
I'll send a PR later.
