### ISSUE TITLE
Web pages that cause errors

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#49]
This issue is meant to tracking down the website that microProxy can not serve correctly.

**Comment by mike820324** [comment]
**URL:**
http://images.apple.com/media/us/tv/2015/5a9ed275-a0b2-4dcb-8eeb-5596f684945c/films/feature/tv-feature-cc-us-20150909_1280x720h.mp4

**Environment:**
Linux mint 
microProxy master branch

**What Went Wrong:**
Need to wait a very long time for the browser to play the video

**Comment by mike820324** [comment]
**URL:**
http://lawerhome.tw.quickconnect.to

**Environment:**
Linux mint 
microProxy master branch

**What Went Wrong:**
Proxy will throw the following exceptions. Connection is normal thourgh.

```
Traceback (most recent call last):
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/proxy.py", line 33, in handle_stream
    dest_stream = yield self.proxy_server_handler.create_dest_stream(host, port)
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/proxy.py", line 74, in create_dest_stream
    yield gen.with_timeout(datetime.timedelta(5), dest_stream.connect((host, port)))
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
StreamClosedError: Stream is closed
```

```
2016-06-08 10:24:13,130 - microproxy.proxy - ERROR - [Errno -9] Address family for hostname not supported
Traceback (most recent call last):
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/proxy.py", line 115, in handle_stream
    yield layer_manager.start_layer()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/proxy.py", line 38, in start_layer
    current_context = yield current_layer.process_and_return_context()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/layer/proxy/socks.py", line 50, in process_and_return_context
    dest_stream = yield self.socks_response_with_dest_stream_creation(host, port, addr_type)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/layer/proxy/socks.py", line 118, in socks_response_with_dest_stream_creation
    dest_stream = self.create_dest_stream((host, port))
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/layer/proxy/base.py", line 20, in create_dest_stream
    dest_socket.connect(dest_addr_info)
  File "<string>", line 1, in connect
gaierror: [Errno -9] Address family for hostname not supported
```

**Comment by mike820324** [comment]
**URL:**
http://www.csie.ncu.edu.tw

**Environment:**
Linux mint 
microProxy master branch

**What Went Wrong:**
Will hang on some resources.  
This problem can not always reproduce.

**Comment by mike820324** [comment]
PR #101 and PR #100 fix this issue.
