### ISSUE TITLE
[TlsLayer]: IOStream is not idle problem

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#53]
In my linux machine, connecting to https website may see the following error.

```
2016-05-19 09:36:58,270 - microproxy.layer.tls - ERROR - IOStream is not idle; cannot convert to SSL
Traceback (most recent call last):
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/layer/tls.py", line 22, in process
    src_stream = yield self.context.src_stream.start_tls(server_side=True, ssl_options=src_ssl_context)
  File "/home/mike820324/ProgrammingEnv/python/microProxy/site-packages/tornado/iostream.py", line 1131, in start_tls
    raise ValueError("IOStream is not idle; cannot convert to SSL")
ValueError: IOStream is not idle; cannot convert to SSL
```

This bug may not be easy to reproduce.

**Comment by mike820324** [comment]
The following are some reference that may be helpful.

https://gist.github.com/weaver/293449
https://kura.io/2013/07/31/writing-the-starttls-command-in-to-blackhole/

Which they will call the following function before changing into tls socket.

```
current_loop.remove_handler(src_stream)
```

**Comment by mike820324** [comment]
I may find a way to reproduce the problem. Try to use firefox and open the following tabs.
- https://www.apple.com
- http://www.bbc.com
- http://www.asus.com/TW/
- http://www.acer.com/ac/en/US/content/home
- http://www.cs.nctu.edu.tw/cswebsite/
- https://www.synology.com/en-global/products/DS916+

reload all these tabs at once, and there is a very high possiblity that this bug will be triggered.

**Comment by mike820324** [comment]
commit 4c7cf6b fix this issue.
