### ISSUE TITLE
[TlsLayer]: ERROR - name must be a byte string

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#66]
When connecting to ip based website with https, the following error shows up.

```
2016-06-08 10:08:41,305 - microproxy.proxy - ERROR - name must be a byte string
Traceback (most recent call last):
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/proxy.py", line 115, in handle_stream
    yield layer_manager.start_layer()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/proxy.py", line 38, in start_layer
    current_context = yield current_layer.process_and_return_context()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy/microproxy/layer/application/tls.py", line 87, in process_and_return_context
    ssl_options=src_ssl_ctx)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
TypeError: name must be a byte string
```

**Comment by mike820324** [comment]
`self.ssl_sock.set_tlsext_host_name(self.hostname)` take a valid hostname, but sometimes, the browser may not send a sni to us, and causing the problem.

**Comment by mike820324** [comment]
commit f05c84d fix this issue.
