### ISSUE TITLE
Need Refine Error Handling

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#8]
Please reference the stacktrace, no error handling on the socket or zmq.
These may cause serious trouble when exception occured.

```
ERROR:tornado.application:Uncaught
 exception, closing connection.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/han-pc/workspace/python/microProxy/proxy.py", line 228, in on_dest_connect
    HttpLayer(self.src_stream, self.dest_stream)
  File "/Users/han-pc/workspace/python/microProxy/proxy.py", line 53, in __init__
    zmq_socket = context.socket(zmq.REQ)
  File "/Library/Python/2.7/site-packages/zmq/sugar/context.py", line 138, in socket
    s = self._socket_class(self, socket_type)
  File "zmq/backend/cython/socket.pyx", line 279, in zmq.backend.cython.socket.Socket.__cinit__ (zmq/backend/cython/socket.c:3384)
ZMQError: Too many open files
ERROR:tornado.application:Exception in callback <functools.partial object at 0x10142bb50>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/han-pc/workspace/python/microProxy/proxy.py", line 228, in on_dest_connect
    HttpLayer(self.src_stream, self.dest_stream)
  File "/Users/han-pc/workspace/python/microProxy/proxy.py", line 53, in __init__
    zmq_socket = context.socket(zmq.REQ)
  File "/Library/Python/2.7/site-packages/zmq/sugar/context.py", line 138, in socket
    s = self._socket_class(self, socket_type)
  File "zmq/backend/cython/socket.pyx", line 279, in zmq.backend.cython.socket.Socket.__cinit__ (zmq/backend/cython/socket.c:3384)
ZMQError: Too many open files
```

**Comment by chhsiao90** [comment]
```
ERROR:tornado.application:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/han/microProxy/proxy.py", line 224, in on_dest_connect
    self.src_stream.write(response)
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 377, in write
    self._check_closed()
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 885, in _check_closed
    raise StreamClosedError(real_error=self.error)
StreamClosedError: Stream is closed
ERROR:tornado.application:Exception in callback <functools.partial object at 0x7fe268031e68>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 600, in _run_callback
    ret = callback()
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 554, in wrapper
    return callback(*args)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/han/microProxy/proxy.py", line 224, in on_dest_connect
    self.src_stream.write(response)
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 377, in write
    self._check_closed()
  File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 885, in _check_closed
```

**Comment by chhsiao90** [comment]
```
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/han/microProxy/proxy.py", line 79, in on_zmq_recv
    for chunk in self.http_response.data:
  File "/home/han/microProxy/http.py", line 132, in data
    yield b"{0}{1}".format(self._assemble_header(), self.body)
  File "/home/han/microProxy/http.py", line 100, in _assemble_header
    http_header_fields = [ "{0}: {1}".format(key, self.header[key]) for key in self.header ]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-25: ordinal not in range(128)
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/han/microProxy/proxy.py", line 79, in on_zmq_recv
    for chunk in self.http_response.data:
  File "/home/han/microProxy/http.py", line 132, in data
    yield b"{0}{1}".format(self._assemble_header(), self.body)
  File "/home/han/microProxy/http.py", line 100, in _assemble_header
    http_header_fields = [ "{0}: {1}".format(key, self.header[key]) for key in self.header ]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-25: ordinal not in range(128)
ERROR:tornado.application:Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/han/microProxy/proxy.py", line 79, in on_zmq_recv
    for chunk in self.http_response.data:
  File "/home/han/microProxy/http.py", line 132, in data
    yield b"{0}{1}".format(self._assemble_header(), self.body)
  File "/home/han/microProxy/http.py", line 100, in _assemble_header
    http_header_fields = [ "{0}: {1}".format(key, self.header[key]) for key in self.header ]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 22-25: ordinal not in range(128)
```

**Comment by mike820324** [comment]
About the second error message. We need to add error handling in socks proxy layer.
Espeicailly when read/write data to stream.

**Comment by mike820324** [comment]
As for the third error, some connection headers may contains unicode encoding character and as a result causing the header assemble process failed.
Please see issue #10 for more detail.

**Comment by mike820324** [comment]
We need to find a way to throw and catch connection timeout.

**Comment by mike820324** [comment]
Will add timeout when connecting to dest_stream, that's all.
