### ISSUE TITLE
[TlsLayer]: Encounter "Transport endpoint is not connected" error

### ISSUE THREAD

**Issue by mike820324** [mike820324/microProxy#85]
While testing the http2 functionality with https://http2.akamai.com/demo, I have encounter the following error.

```
2016-06-30 11:34:43,895 - iostream                       - WARNING  - SSL Error on 15 (not connected): [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad certificate')]
2016-06-30 11:34:43,907 - proxy                          - ERROR    - [Errno 107] Transport endpoint is not connected
Traceback (most recent call last):
  File "/home/mike820324/SourceCode/myProject/microProxy-framework/microProxy/microproxy/proxy.py", line 109, in handle_stream
    yield self.layer_manager.run_layers(stream)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy-framework/microProxy/microproxy/proxy.py", line 29, in run_layers
    current_context = yield current_layer.process_and_return_context()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/mike820324/SourceCode/myProject/microProxy-framework/microProxy/microproxy/layer/application/tls.py", line 183, in process_and_return_context
    server_side=True, ssl_options=src_ssl_ctx)
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/mike820324/ProgrammingEnv/python/pypy-microProxy/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
error: [Errno 107] Transport endpoint is not connected
```

Using wireshark, I found out that the certificate is not complete which cause firefox reject the certificate.

**Comment by mike820324** [comment]
Reference #54

**Comment by mike820324** [comment]
The firefox security debug console shows the following message

> An error occurred during a connection to www.google.com.
> You have received an invalid certificate.  Please contact the server administrator or email correspondent and give them the following information:
> Your certificate contains the same serial number as another certificate issued by the certificate authority.  Please get a new certificate containing a unique serial number.
> Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL
