### ISSUE TITLE
[SocksLayer]: socks layer failed with curl client

### ISSUE THREAD

**Issue by chhsiao90** [mike820324/microProxy#93]
```
Traceback (most recent call last):
  File "/Users/han-pc/workspace/python/microProxy/microproxy/proxy.py", line 111, in handle_stream
    yield self.layer_manager.run_layers(stream)
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/proxy.py", line 31, in run_layers
    current_context = yield current_layer.process_and_return_context()
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/layer/proxy/socks.py", line 47, in process_and_return_context
    yield self.socks_greeting()
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/han-pc/.env/mp/lib/python2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/Users/han-pc/workspace/python/microProxy/microproxy/layer/proxy/socks.py", line 72, in socks_greeting
    raise ProtocolError("socks5 auth not supported")
ProtocolError: socks5 auth not supported

```

**Comment by mike820324** [comment]
commit 2339b88 fix this issue.
